version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -No -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    build:
      context: .
      dockerfile: TaskTracker.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TaskTrackerDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
  worker:
    build:
      context: .
      dockerfile: TaskTracker.Worker/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TaskTrackerDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
